Add Browser Notifications
alcalyn/hex pull request #7
Opened 2024-03-22 01:24 UTC by ursi

- Add notifications for when an opponent makes a move
- Add notifications for when a game starts

2024-03-22 11:51 UTC, alcalyn requested changes

2024-03-22 19:05 UTC, ursi commented on src/client/vue/App.vue
> +Notification.requestPermission();
where do you get this error?

2024-03-22 19:19 UTC, alcalyn commented on src/client/vue/App.vue
> +Notification.requestPermission();
From the linter, with yarn lint

2024-03-22 19:46 UTC, ursi commented
I improved things quite a bit. I'm sure there are little things wrong, as I'm not a TS or vue dev, but hopefully they are trivial fixes.

2024-03-23 19:50 UTC, alcalyn commented on src/client/notifications.ts
> +const sendNotification = (options, route) => {
To define arguments typings:

```suggestion
const sendNotification = (options: NotificationOptions, route: () => void) => {
```

2024-03-23 19:50 UTC, alcalyn commented on src/client/notifications.ts
> +        };
I checked the error, it's not because `Notification` is not defined, but just the constructor throw an error on mobile.
- Just catch the error
- also `focus();` seems not taking argument

```suggestion
        try {
            new Notification('PlayHex', { ...options, icon }).onclick = function() {
                if (route) route();
                focus();
                this.close();
            };
        } catch (e) {
            // TODO check compatibility on mobile. https://stackoverflow.com/questions/29774836/failed-to-construct-notification-illegal-constructor
        }
```

2024-03-23 19:51 UTC, merged

2024-03-23 20:00 UTC, alcalyn commented
Thanks ! That's good. I applied theses suggestions.